### ISSUE TITLE
Docker information

### ISSUE THREAD

**Issue by SergiAguilo** [CARE-SM/CARE-SM-Toolkit#2]
Hi,

I am trying to deploy the following docke compose:

```
version: "3.3"

services:
  api:
    image: pabloalarconm/care-sm-toolkit:0.1.6 # check for latest version
    ports:
      - "8000:8000"
    volumes:
      - ./data:/code/data
```
But I don't know which endpoints I need to ask to make the data transformation, as the default url [http://0.0.0.0:8000 ](http://0.0.0.0:8000) don't do anything. Can you add more information in the README?

Thanks!
